### ISSUE TITLE
Notice from CRAN about 'additional issues' (OpenBLAS?)

### ISSUE THREAD

**Issue by skyebend** [statnet/tsna#3]

**Comment by skyebend** [comment]
https://www.stats.ox.ac.uk/pub/bdr/Rblas/OpenBLAS/tsna.out
```
 Error: Test failed: 'all sna stats used by tSnaStats can be called'
  * Lapack routine dgesv: system is exactly singular: U[4,4] = 0
  Backtrace:
   1. tsna::tSnaStats(moodyContactSim, funName, start = 600, time.interval = 50)
   2. base::lapply(...)
   3. tsna:::FUN(X[[i]], ...)
   7. base::solve.default(A, tol = tol)
  Execution halted
```
it says that the OpenBLAS tests are:

Tests using R-devel on x86_64 Fedora 30 Linux with alternative BLAS/LAPACK
implementations. Except as noted below, R was configured as per
https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-devel-linux-x86_64-fedora-gcc

ATLAS:
Serial ATLAS using the Fedora shared libraries. (Currently version 3.10.3.)
libRblas.so was replaced by a symlink to /usr/lib64/atlas/libsatlas.so
(so the LAPACK in the R sources was used).
In earlier tests, similar results were obtained using ATLAS libs 
for the LAPACK and with a static BLAS (only).

MKL:
Intel MKL 2019 update 5 used to build Rblas and also providing LAPACK (which is 
version 3.7.0).  R was configured by (csh script)

setenv MKL_LIB_PATH /usr/local/MKL/mkl/lib/intel64
setenv LD_LIBRARY_PATH $MKL_LIB_PATH
setenv MKL "-L$MKL_LIB_PATH -lmkl_gf_lp64 -lmkl_core -lmkl_sequential"
~/R/svn/R-devel/configure -C --with-blas="$MKL" --with-lapack

OpenBLAS:

Serial OpenBLAS using the Fedora shared libraries (currently version 0.3.7).
libRblas.so was replaced by a symlink to /usr/lib64/libopenblas.so (part of
openblas-devel, linked from openblas-serial).

**Comment by skyebend** [comment]
I think what is going on here is that tsna is asking sna to compute a network metric on a network of size zero or 1.  With the standard linear algebra this edgecase must be intercepted but OpenBLAS does something different. not sure how to resolve.  sna doesn't agree that networks of size zero exist, so probably can't handle there ... need to trap the offending case and return whatever the non-OpenBLAS libs do?  This will be hard, since this is a wrapper function that isn't supposed to know much about the sna functions it is calling

**Comment by CarterButts** [comment]
Interesting that this is not a problem that cropped up until now, if the root issue is that size-zero networks are being passed to sna.  Wouldn't that have happened before?

It is possibly possible to harden many/most sna routines to handle degenerate networks, though it is not always easy to know what to do with them (since many properties are simply undefined for such networks).  When that package was created, the idea that someone would want to calculate statistics on graphs of size 0 (or even 1) was bizarre, and my view has historically been that it's up to the user to catch those cases (since they are generally undefined even in principle).  However, there are special cases where networks with vertex dynamics can become degenerate (in the sense of having no vertices), which I assume to be the problem here.

If we need to change sna, that will need to wait until late December (because of travel and other obligations).  However, I have been contemplating trying to push out another minor sna update by early January (since I am using it in my class, and there are some things that I didn't have time to put into the most recent update), so that could be a target.....

**Comment by skyebend** [comment]
I'm trying to get over my frustration that tsna is being threatened to be archived for what appears to be exposing a 'bug' in another package that only appears when using a non-standard platform configuration none of us have attempted or agreed support :-)

 I guess I will start by trying to get OpenBLAS installed locally, if I can get a reproducible test case I pass it to Carter

```
Tests using R-devel on x86_64 Fedora 30 Linux with alternative BLAS/LAPACK
implementations. Except as noted below, R was configured as per
https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-devel-linux-x86_64-fedora-gcc

OpenBLAS:

Serial OpenBLAS using the Fedora shared libraries (currently version 0.3.7).
libRblas.so was replaced by a symlink to /usr/lib64/libopenblas.so (part of
openblas-devel, linked from openblas-serial).
```

**Comment by CarterButts** [comment]
Well, I suppose another option would be to alter the CRAN version of the test so that it never evaluates zero-size networks.  Not glamorous, but if the package is being threatened about cases that we're not trying to support in the first place, one could view the issue as being that our tests are overbroad.

**Comment by skyebend** [comment]
I think I've got OpenBLAS installed
```
> extSoftVersion()["BLAS"]
                                             BLAS 
"/usr/lib/x86_64-linux-gnu/openblas/libblas.so.3" 
```
but not able to reproduce the problem to isolate which function is triggering it.  Attempting to resubmit with a "skip this test on CRAN" option..

**Comment by skyebend** [comment]
release was accepted by CRAN
